spring.application.name=stc-system
server.port=8080
server.servlet.context-path=/

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:Database/STC_Attendance_System.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Logging
logging.level.root=INFO
logging.level.com.stc=DEBUG

# Server configuration
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html
